pipeline {
    agent any
    triggers {
        cron('H */3 * * *')   // runs every 3 hours
    }

    // tools {
    // jdk 'jdk21'
    //     maven 'maven3'
    // }
    environment {
        SONAR_TOKEN = credentials('sonarcloud-token')
        IMAGE_NAME = 'yourdockerhub/image-name'
        KUBECONFIG = "/var/lib/jenkins/.kube/config"
    }

    stages {
        stage('Backend Build') {
            steps {
                dir('smart-appointment-booking-full/backend') {
                    sh './mvnw clean package -DskipTests'
                }
            }
        }
        stage('Backend Test') {
            steps {
                dir('smart-appointment-booking-full/backend') {
                    sh './mvnw test'
                }
            }
        }
        stage('Frontend Build') {
            steps {
                sh 'cd smart-appointment-booking-full/frontend && npm install'
                sh 'cd smart-appointment-booking-full/frontend && npm run build'
            }
        }
        stage('SonarCloud Analysis') {
            steps {
                dir('smart-appointment-booking-full/backend') {
                    withSonarQubeEnv('SonarCloud') {
                        sh "./mvnw sonar:sonar \
                            -Dsonar.organization=nilayshekhar \
                            -Dsonar.projectKey=nilayshekhar_devops \
                            -Dsonar.projectName=nilayshekhar_devops \
                            -Dsonar.host.url=https://sonarcloud.io \
                            -Dsonar.login=$SONAR_TOKEN"
                    }
                }
            }
        }
        stage('Docker Build') {
            steps {
                script {
                    echo "Building Docker images..."
                    sh 'docker version'
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        sh "docker-compose build"
                    }
                }
            }
        }
        stage('Docker Push') {
            steps {
                script {
                    echo "Pushing images to DockerHub..."
                    withDockerRegistry(credentialsId: 'docker-cred') {
                        sh "docker push nilayshekhar/smart-appointment-backend:latest"
                        sh "docker push nilayshekhar/smart-appointment-frontend:latest"
                    }
                }
            }
        }
        stage('Update Kubernetes Manifests') {
            steps {
                script {
                    echo "Substituting Docker image tag in k8s YAML..."
                    sh "sed -i 's@IMAGE_NAME@nilayshekhar/smart-appointment-backend:latest@g' k8s/backend-deployment.yaml"
                    sh "sed -i 's@IMAGE_NAME@nilayshekhar/smart-appointment-frontend:latest@g' k8s/frontend-deployment.yaml"
                }
            }
        }
        stage('Deploy to Kubernetes') {
            steps {
                script {
                    echo "Applying Kubernetes Deployment..."
                    sh "kubectl --kubeconfig=${KUBECONFIG} apply -f k8s/backend-deployment.yaml --validate=false"
                    sh "kubectl --kubeconfig=${KUBECONFIG} apply -f k8s/backend-service.yaml --validate=false"
                    sh "kubectl --kubeconfig=${KUBECONFIG} apply -f k8s/frontend-deployment.yaml --validate=false"
                    sh "kubectl --kubeconfig=${KUBECONFIG} apply -f k8s/frontend-service.yaml --validate=false"
                    echo "Waiting for backend deployment to finish rolling out..."
                    sh "kubectl --kubeconfig=${KUBECONFIG} rollout status deployment/backend-deployment"
                    echo "Waiting for frontend deployment to finish rolling out..."
                    sh "kubectl --kubeconfig=${KUBECONFIG} rollout status deployment/frontend-deployment"
                }
            }
        }
        stage('Verify Deployment') {
            steps {
                script {
                    sh "kubectl --kubeconfig=${KUBECONFIG} get pods"
                    sh "kubectl --kubeconfig=${KUBECONFIG} get svc"
                }
            }
        }
    }
    post {
        success {
            mail to: 'nilayshekhar16@gmail.com',
                 subject: 'Jenkins Deployment SUCCESS',
                 body: "Deployment completed successfully and is available at http://your-app-url"
        }
        failure {
            mail to: 'nilayshekhar16@gmail.com',
                 subject: 'Jenkins Deployment FAILED',
                 body: "Deployment failed on Jenkins server."
        }
    }
}
