pipeline {
    agent any
    environment {
        SONARQUBE_SERVER = 'SonarQube'
        SONARQUBE_TOKEN = credentials('sonarqube-token')
    }
    triggers {
        cron('H H/6 * * *')
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/nilayshekhar/devops.git'
            }
        }
        stage('Backend Build') {
            steps {
                sh './backend/mvnw clean install'
            }
        }
        stage('Frontend Build') {
            steps {
                sh 'cd frontend && npm install'
                sh 'cd frontend && npm run build'
            }
        }
        stage('SonarQube Analysis') {
            steps {
                withSonarQubeEnv('SonarQube') {
                    sh './backend/mvnw sonar:sonar -Dsonar.login=$SONARQUBE_TOKEN'
                }
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker-compose build'
            }
        }
        stage('Docker Deploy') {
            steps {
                sh 'docker-compose up -d --build'
            }
        }
    }
    post {
        success {
            echo 'Deployment successful! Access the app at http://localhost:8080/'
        }
        failure {
            echo 'Deployment failed.'
        }
    }
}
